services:
  - type: web
    name: cartcorner-backend
    env: node
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: node index.js
    nodeVersion: 16.20.0
    envVars:
      - key: NODE_VERSION
        value: 16.20.0
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"
      - key: SHARP_DISTRO
        value: "alpine"
